version: '3.8'  

services:
  db:
    container_name: exercises_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lihobor0754133
      POSTGRES_DB: exercises
    ports:
      - "5432:5432"
  app:
    container_name: exercise_tracker
    build: ./
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:@exercises_db:5432/exercise
    volumes:
      - ./app:/code/app 
    depends_on:
      - db
  redis:
    container_name: redis_for_exercises
    image: redis:7