"""remove some fields from exercise mode

Revision ID: 595a65b06e01
Revises: 136ee5c91f51
Create Date: 2024-10-29 04:20:21.018505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595a65b06e01'
down_revision: Union[str, None] = '136ee5c91f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'weight')
    op.drop_column('exercise', 'reps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
